
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class Remove extends javax.swing.JFrame {

    /**
     * Creates new form Remove
     */
    public Remove() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundPanel = new javax.swing.JPanel();
        HeaderPanel = new javax.swing.JPanel();
        HeadlineLabel = new javax.swing.JLabel();
        HomeButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        itemComboBox = new javax.swing.JComboBox<>();
        brandComboBox = new javax.swing.JComboBox<>();
        amountTextField = new javax.swing.JTextField();
        AmountLabel = new javax.swing.JLabel();
        BrandLabel = new javax.swing.JLabel();
        ItemLabel = new javax.swing.JLabel();
        RemoveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remove Inventory");

        BackgroundPanel.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HeaderPanel.setBackground(new java.awt.Color(0, 255, 204));

        HeadlineLabel.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        HeadlineLabel.setForeground(new java.awt.Color(255, 255, 255));
        HeadlineLabel.setText("INVENTORY SYSTEM");

        javax.swing.GroupLayout HeaderPanelLayout = new javax.swing.GroupLayout(HeaderPanel);
        HeaderPanel.setLayout(HeaderPanelLayout);
        HeaderPanelLayout.setHorizontalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(HeadlineLabel)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        HeaderPanelLayout.setVerticalGroup(
            HeaderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(HeadlineLabel)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        BackgroundPanel.add(HeaderPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 110));

        HomeButton.setText("Home");
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        BackgroundPanel.add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        BackgroundPanel.add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, -1, -1));

        itemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pens (blue)", "Pens (red)", "Pens (black)", "Text Books 40p", "Text Books 80p", "Text Books 120p" }));
        itemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemComboBoxActionPerformed(evt);
            }
        });
        BackgroundPanel.add(itemComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, -1, -1));

        brandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atlas", "Richard" }));
        BackgroundPanel.add(brandComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));
        BackgroundPanel.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 70, -1));

        AmountLabel.setText("Amount");
        BackgroundPanel.add(AmountLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, -1, -1));

        BrandLabel.setText("Brand");
        BackgroundPanel.add(BrandLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, -1, -1));

        ItemLabel.setText("Item");
        BackgroundPanel.add(ItemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        RemoveButton.setText("Remove");
        RemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveButtonActionPerformed(evt);
            }
        });
        BackgroundPanel.add(RemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        new Homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void itemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemComboBoxActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        String item = itemComboBox.getSelectedItem().toString();
        String brand = brandComboBox.getSelectedItem().toString();
        String amount = amountTextField.getText();
        
        try{
           Statement stmt = NewClass.getConnection().createStatement(); 
           String query1 = "SELECT amount FROM item WHERE iName='"+item+"' and iBrand='"+brand+"';";
           ResultSet rs = stmt.executeQuery(query1);
           int n1 =0;
           while(rs.next())
               n1 = rs.getInt("amount");
           int n2 = Integer.parseInt(amount);	
           int n3 = n1 - n2;
           
           if(n3 < 0){
               n3 = 0;
               JOptionPane.showMessageDialog(this, "Not enough in the inventory! Only "+n1+" is going to get removed!");
           }
           String query = "UPDATE item SET amount = '"+n3+"' WHERE iName='"+item+"' and iBrand='"+brand+"';";
           stmt.executeUpdate(query);
           JOptionPane.showMessageDialog(this, "Successfully Removed");
           String movement = ""+amount+" "+item+" of "+brand+".";
           String query2 = "insert into movement(category,mString) values('Removed','"+movement+"');";
           stmt.executeUpdate(query2);
           
           Statement stm = NewClass.getConnection().createStatement(); 
           String query3 = "SELECT * FROM item WHERE iName='"+item+"' and iBrand='"+brand+"';";
           ResultSet rm = stm.executeQuery(query3);
           int dailySales = 0;
           int supplierId =0;
           while(rm.next()){
               dailySales = rm.getInt("dailySales");
               supplierId = rm.getInt("sId");
           } 
            
           Statement stm1 = NewClass.getConnection().createStatement(); 
           String query4 = "SELECT sTradeTime FROM supplier WHERE sId='"+supplierId+"';";
           ResultSet rd = stm1.executeQuery(query4);
           int leadTime = 0;
           while(rd.next()){
               leadTime = rd.getInt("sTradeTime");
           } 
           
           int a = (leadTime*dailySales);
           
           if(a > n3){
               JOptionPane.showMessageDialog(this, "About to go out of stock! Order ASAP!");
           }
           }
        catch(Exception e){ 
            System.out.println(e);
           }  
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new Homepage().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Remove.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Remove().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountLabel;
    private javax.swing.JButton BackButton;
    private javax.swing.JPanel BackgroundPanel;
    private javax.swing.JLabel BrandLabel;
    private javax.swing.JPanel HeaderPanel;
    private javax.swing.JLabel HeadlineLabel;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel ItemLabel;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JComboBox<String> brandComboBox;
    private javax.swing.JComboBox<String> itemComboBox;
    // End of variables declaration//GEN-END:variables
}
